### ISSUE TITLE
ForEachMethod

### ISSUE THREAD

**Issue by namkilee** [gyuwon/XamarinClass201701#1]
강의 하실 때 ForEachMethod 부분에서 delegate 와 event 에 대해서 설명해주시면서,

기본적인 형태에서 C# 최신 문법에 맞게 최종적인 형태로 변경되는 과정을 설명해주셨었는데,

C# 을 처음 접하다보니 신기하여 집중해서 봤으나... Source 를 보니 중간 과정이 잘 생각이 안납니다. 혹시 시간 되시면, 중간과정도 추가해주시면 감사하겠습니다.

**Comment by gyuwon** [comment]
ForEachMethod 프로젝트에는 다음과 같은 [코드](./source/DelegatesAndEvents/ForEachMethod/Program.cs)가 있습니다.

```csharp
IntAction action = Console.WriteLine;

int sum = 0;
action += n => sum += n;
```

코드조각의 마지막 줄을 `delegate` 문법을 사용해 작성하면 이렇습니다.

```csharp
action += delegate (int n)
{
    sum += n;
};
```

`delegate` 문법을 람다 식 문법으로 변경할 수 있습니다.

```csharp
action += (int n) =>
{
    sum += n;
};
```

컴파일러는 좌항인 `action` 변수를 통해 람다 식 매개변수 형식을 유추할([형 추론, type inference](https://en.wikipedia.org/wiki/Type_inference)) 수 있습니다. 이런 경우 람다 식 매개변수 형식을 생략할 수 있습니다.

```csharp
action += (n) =>
{
    sum += n;
};
```

람다 식에서 매개변수 형식이 생략된 하나의 매개변수에 대해 괄호(`()`)를 생략할 수 있습니다.

```csharp
action += n =>
{
    sum += n;
};
```

하나의 구문(statement)을 가진 람다식은 중괄호(`{}`)와 해당 구문의 세미콜론(`;`)을 생략할 수 있습니다.


```csharp
action += n => sum += n;
```

이 코드는 연산자 사용이 밀집되어 문법에 익숙하지 않은 경우 가독성이 낮다고 평가될 수 있습니다. 그럴 땐 괄호(`()`)를 적절히 사용하면 가독성이 증대되기도 합니다.

```csharp
action += (n => sum += n);
```
